Abort(1) on node 79 (rank 79 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 79
Traceback (most recent call last):
  File "slab_run.py", line 73, in <module>
    image_potential_energy=image.get_potential_energy()
  File "/home/k0227/k022716/ASE/ase_oneapi_2023.0.0/lib64/python3.8/site-packages/ase/atoms.py", line 731, in get_potential_energy
    energy = self._calc.get_potential_energy(self)
  File "/home/k0227/k022716/ASE/ase_oneapi_2023.0.0/lib64/python3.8/site-packages/ase/calculators/calculator.py", line 709, in get_potential_energy
    energy = self.get_property('energy', atoms)
  File "/home/k0227/k022716/ASE/ase_oneapi_2023.0.0/lib64/python3.8/site-packages/ase/calculators/calculator.py", line 737, in get_property
    self.calculate(atoms, [name], system_changes)
  File "/home/k0227/k022716/ASE/ase_oneapi_2023.0.0/lib64/python3.8/site-packages/ase/calculators/calculator.py", line 938, in calculate
    raise CalculationFailed(msg)
ase.calculators.calculator.CalculationFailed: Calculator "espresso" failed with command "mpirun /home/k0227/k022716/QE/src/qe-7.2/bin/pw.x -in Cu-111-5.447902794.pwi > Cu-111-5.447902794.pwo" failed in /home/k0227/k022716/QE/out/Cu/Cu_111/slub with error code 1
